export default {
  CHECK_EMAIL: 'check-email',
  CHECK_PHONE_NUMBER: 'check-phone-number',
  CHECK_REGISTER_SUCCESS: 'check-email-success',
  IS_LOADING_CHECK_REGISTER: 'is-loading-check-email',
  RESET_CHECK_REGISTER: 'reset-check-register',
  REQUEST_OTP_EMAIL: 'request-otp-email',
  REQUEST_OTP_PHONE_NUMBER: 'request-otp-phone-number',
  REQUEST_OTP_EMAIL_SUCCESS: 'request-otp-email-success',
  REQUEST_OTP_PHONE_NUMBER_SUCCESS: 'request-otp-phone-number-success',
  RESET_OTP: 'reset-otp',
  IS_LOADING_REQUEST_OTP: 'is-loading-check-email',
  VERIFY_OTP: 'verify-otp',
  VERIFY_OTP_SUCCESS: 'verify-otp-success',
  RESET_VERIFY_OTP: 'reset-verify-otp',
  IS_LOADING_VERIFY_OTP: 'is-loading-verify-otp',
  REGISTER: 'register',
  REGISTER_SUCCESS: 'register-success',
  IS_LOADING_REGISTER: 'is-loading-register',
};
